version: '3.3'

services:
  rf3d-db:
    container_name: rf3d-db
    image: mysql:5.7
    volumes:
      - ./lib/mysql:/var/lib/mysql
      - ./:/var/www/app
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  rf3d-web:
    container_name: rf3d-web
    build: ./
    ports:
      - 8011:8000
    depends_on:
      - rf3d-db
    volumes:
      - ./:/var/www/app

    working_dir: /var/www/app
    stdin_open: true
    tty: true
    command: app/nut server:run 0.0.0.0:8000